### ISSUE TITLE
Custom Styling

### ISSUE THREAD

**Issue by josephgupkim** [mmotykiewicz/colmar-academy#3]
Apart from the accurately replicated Colmar Academy site, I can't help but wonder what this site would have looked like with your own touch of styling.
I believe this capstone would've been a great chance for you to showcase what you've learned throughout the course and make this Colmar Academy project your own.
Some cool additions would have been:
- Custom fonts
- New color scheme
- Hover effects

**Comment by mmotykiewicz** [comment]
Thanks. Unfortunately, I've been way behind and wasn't finding enough time to work on it. Just wanted to get it to the finish line before the deadline with little "play" in the styling.
There's definitely items I played with and wanted to implement, but ran out of time. 
Life is too busy at the moment!
