### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [mmotykiewicz/colmar-academy#4]
An amazingly well written project that equally looked great on the visual website.
It's unfortunate that I didn't get to see your own touches of design and styling on the site but it was well replicated and gets more than passing marks.

Grade: Exceeds expectation.

**Comment by mmotykiewicz** [comment]
Thanks. Like i mentioned is #3, I unfortunately ran out of time to experiment more with styling due to just life and busy work schedule.
